title: Mi primer sitio de Github
author: Lorenzo Abelenda
email: loreabelenda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Es un sitio de prueba para empezar a usar GitHub pages

# social links
twitter_username: abelenda02 # DO NOT include the @ character, or else the build will fail!
github_username:  loreabelenda # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

---
title: "Pagina 1"
date: 2020-05-09
---
